const pokeData =  [
    {
    "_id": "5ff4fb7cd89993a89cc65444",
    "pokemon": "venusaur-mega",
    "id": 4,
    "species_id": 3,
    "height": 24,
    "weight": 1555,
    "base_experience": 281,
    "type_1": "grass",
    "type_2": "poison",
    "attack": 100,
    "defense": 123,
    "hp": 80,
    "special_attack": 122,
    "special_defense": 120,
    "speed": 80,
    "ability_1": "thick-fat",
    "ability_2": "NA",
    "ability_hidden": "NA",
    "color_1": "#78C850",
    "color_2": "#A040A0",
    "color_f": "#81A763",
    "egg_group_1": "monster",
    "egg_group_2": "plant",
    "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/003_f2.png",
    "generation_id": "NA",
    "evolves_from_species_id": "NA",
    "evolution_chain_id": "NA",
    "shape_id": "NA",
    "shape": "NA",
    "pokebase": "venusaur",
    "pokedex": "http://www.pokemon.com/us/pokedex/venusaur"
    },
    {
    "_id": "5ff4fb7cd89993a89cc65445",
    "pokemon": "charizard-mega-x",
    "id": 8,
    "species_id": 6,
    "height": 17,
    "weight": 1105,
    "base_experience": 285,
    "type_1": "fire",
    "type_2": "dragon",
    "attack": 130,
    "defense": 111,
    "hp": 78,
    "special_attack": 130,
    "special_defense": 85,
    "speed": 100,
    "ability_1": "tough-claws",
    "ability_2": "NA",
    "ability_hidden": "NA",
    "color_1": "#F08030",
    "color_2": "#7038F8",
    "color_f": "#D06E60",
    "egg_group_1": "monster",
    "egg_group_2": "dragon",
    "url_image": "http://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f2.png",
    "generation_id": "NA",
    "evolves_from_species_id": "NA",
    "evolution_chain_id": "NA",
    "shape_id": "NA",
    "shape": "NA",
    "pokebase": "charizard",
    "pokedex": "http://www.pokemon.com/us/pokedex/charizard"
    }
    ]


    export default pokeData;